import { IBlog } from '../types/blog';

export const blogData: IBlog[] = [
	{
		blogId: '1',
		title: 'Twitter',
		text: 'Connect your Twitter feed to your Marico homepage.',
		finish: true,
		discount: { isDiscount: false, percentNum: 0 },
		chooseSubscription: [
			{
				title: 'Personal',
				text: 'Ideal for individual developers, education and open source communities.',
				price: 0,
				subopportunity: '',
				opportunity: [
					'Twitter Desktop',
					'Unlimited public repositories',
					'Twitter Engine + Kubernetes',
					'200 image pulls per 6 hours',
					'Unlimited scoped tokens',
				],
			},
			{
				title: 'Pro',
				text: 'Includes pro tools for individual developers who want to accelerate their productivity.',
				price: 60,
				subopportunity: 'Everything in Personal plus:',
				opportunity: [
					'Unlimited private repositories',
					'5,000 image pulls per day',
					'5 concurrent builds',
					'300 Hub vulnerability scans',
				],
			},
			{
				title: 'Expert',
				text: 'Ideal for expert and include capabilitie for collaboration and productivity.',
				price: 160,
				subopportunity: 'Everything in Pro plus:',
				opportunity: [
					'Up to 100 users',
					'Unlimited teams',
					'15 concurrent builds',
					'Add users in bulk',
					'Audit logs',
				],
			},
		],
	},
	{
		blogId: '2',
		title: 'YouTube',
		text: 'Connect your YouTube feed to your Marico homepage.',
		finish: true,
		discount: { isDiscount: false, percentNum: 0 },
		chooseSubscription: [
			{
				title: 'Personal',
				text: 'Ideal for individual developers, education and open source communities.',
				price: 0,
				subopportunity: '',
				opportunity: [
					'YouTube Desktop',
					'Unlimited public repositories',
					'YouTube Engine + Kubernetes',
					'200 image pulls per 6 hours',
					'Unlimited scoped tokens',
				],
			},
			{
				title: 'Pro',
				text: 'Includes pro tools for individual developers who want to accelerate their productivity.',
				price: 60,
				subopportunity: 'Everything in Personal plus:',
				opportunity: [
					'Unlimited private repositories',
					'5,000 image pulls per day',
					'5 concurrent builds',
					'300 Hub vulnerability scans',
				],
			},
			{
				title: 'Expert',
				text: 'Ideal for expert and include capabilitie for collaboration and productivity.',
				price: 160,
				subopportunity: 'Everything in Pro plus:',
				opportunity: [
					'Up to 100 users',
					'Unlimited teams',
					'15 concurrent builds',
					'Add users in bulk',
					'Audit logs',
				],
			},
		],
	},
	{
		blogId: '3',
		title: 'WordPress',
		text: 'Connect your WordPress feed to your Marico homepage.',
		finish: true,
		discount: { isDiscount: false, percentNum: 0 },
		chooseSubscription: [
			{
				title: 'Personal',
				text: 'Ideal for individual developers, education and open source communities.',
				price: 0,
				subopportunity: '',
				opportunity: [
					'WordPress Desktop',
					'Unlimited public repositories',
					'WordPress Engine + Kubernetes',
					'200 image pulls per 6 hours',
					'Unlimited scoped tokens',
				],
			},
			{
				title: 'Pro',
				text: 'Includes pro tools for individual developers who want to accelerate their productivity.',
				price: 60,
				subopportunity: 'Everything in Personal plus:',
				opportunity: [
					'Unlimited private repositories',
					'5,000 image pulls per day',
					'5 concurrent builds',
					'300 Hub vulnerability scans',
				],
			},
			{
				title: 'Expert',
				text: 'Ideal for expert and include capabilitie for collaboration and productivity.',
				price: 160,
				subopportunity: 'Everything in Pro plus:',
				opportunity: [
					'Up to 100 users',
					'Unlimited teams',
					'15 concurrent builds',
					'Add users in bulk',
					'Audit logs',
				],
			},
		],
	},
	{
		blogId: '4',
		title: 'Substack',
		text: 'Connect your Substack feed to your Marico homepage.',
		finish: true,
		discount: { isDiscount: false, percentNum: 0 },
		chooseSubscription: [
			{
				title: 'Personal',
				text: 'Ideal for individual developers, education and open source communities.',
				price: 0,
				subopportunity: '',
				opportunity: [
					'Substack Desktop',
					'Unlimited public repositories',
					'Substack Engine + Kubernetes',
					'200 image pulls per 6 hours',
					'Unlimited scoped tokens',
				],
			},
			{
				title: 'Pro',
				text: 'Includes pro tools for individual developers who want to accelerate their productivity.',
				price: 60,
				subopportunity: 'Everything in Personal plus:',
				opportunity: [
					'Unlimited private repositories',
					'5,000 image pulls per day',
					'5 concurrent builds',
					'300 Hub vulnerability scans',
				],
			},
			{
				title: 'Expert',
				text: 'Ideal for expert and include capabilitie for collaboration and productivity.',
				price: 160,
				subopportunity: 'Everything in Pro plus:',
				opportunity: [
					'Up to 100 users',
					'Unlimited teams',
					'15 concurrent builds',
					'Add users in bulk',
					'Audit logs',
				],
			},
		],
	},
	{
		blogId: '5',
		title: 'Medium',
		text: 'Connect your Medium feed to your Marico homepage.',
		finish: true,
		discount: { isDiscount: false, percentNum: 0 },
		chooseSubscription: [
			{
				title: 'Personal',
				text: 'Ideal for individual developers, education and open source communities.',
				price: 0,
				subopportunity: '',
				opportunity: [
					'Medium Desktop',
					'Unlimited public repositories',
					'Medium Engine + Kubernetes',
					'200 image pulls per 6 hours',
					'Unlimited scoped tokens',
				],
			},
			{
				title: 'Pro',
				text: 'Includes pro tools for individual developers who want to accelerate their productivity.',
				price: 60,
				subopportunity: 'Everything in Personal plus:',
				opportunity: [
					'Unlimited private repositories',
					'5,000 image pulls per day',
					'5 concurrent builds',
					'300 Hub vulnerability scans',
				],
			},
			{
				title: 'Expert',
				text: 'Ideal for expert and include capabilitie for collaboration and productivity.',
				price: 160,
				subopportunity: 'Everything in Pro plus:',
				opportunity: [
					'Up to 100 users',
					'Unlimited teams',
					'15 concurrent builds',
					'Add users in bulk',
					'Audit logs',
				],
			},
		],
	},
	{
		blogId: '6',
		title: 'RSS Feeds',
		text: 'Connect your RSS feed to your Marico homepage.',
		finish: true,
		discount: { isDiscount: false, percentNum: 0 },
		chooseSubscription: [
			{
				title: 'Personal',
				text: 'Ideal for individual developers, education and open source communities.',
				price: 0,
				subopportunity: '',
				opportunity: [
					'RSS Feeds Desktop',
					'Unlimited public repositories',
					'RSS Feeds Engine + Kubernetes',
					'200 image pulls per 6 hours',
					'Unlimited scoped tokens',
				],
			},
			{
				title: 'Pro',
				text: 'Includes pro tools for individual developers who want to accelerate their productivity.',
				price: 60,
				subopportunity: 'Everything in Personal plus:',
				opportunity: [
					'Unlimited private repositories',
					'5,000 image pulls per day',
					'5 concurrent builds',
					'300 Hub vulnerability scans',
				],
			},
			{
				title: 'Expert',
				text: 'Ideal for expert and include capabilitie for collaboration and productivity.',
				price: 160,
				subopportunity: 'Everything in Pro plus:',
				opportunity: [
					'Up to 100 users',
					'Unlimited teams',
					'15 concurrent builds',
					'Add users in bulk',
					'Audit logs',
				],
			},
		],
	},
	{
		blogId: '7',
		title: 'Spotify',
		text: 'Connect your Spotify feed to your Marico homepage.',
		finish: true,
		discount: { isDiscount: false, percentNum: 0 },
		chooseSubscription: [
			{
				title: 'Personal',
				text: 'Ideal for individual developers, education and open source communities.',
				price: 0,
				subopportunity: '',
				opportunity: [
					'Spotify Desktop',
					'Unlimited public repositories',
					'Spotify Feeds Engine + Kubernetes',
					'200 image pulls per 6 hours',
					'Unlimited scoped tokens',
				],
			},
			{
				title: 'Pro',
				text: 'Includes pro tools for individual developers who want to accelerate their productivity.',
				price: 60,
				subopportunity: 'Everything in Personal plus:',
				opportunity: [
					'Unlimited private repositories',
					'5,000 image pulls per day',
					'5 concurrent builds',
					'300 Hub vulnerability scans',
				],
			},
			{
				title: 'Expert',
				text: 'Ideal for expert and include capabilitie for collaboration and productivity.',
				price: 160,
				subopportunity: 'Everything in Pro plus:',
				opportunity: [
					'Up to 100 users',
					'Unlimited teams',
					'15 concurrent builds',
					'Add users in bulk',
					'Audit logs',
				],
			},
		],
	},
	{
		blogId: '8',
		title: 'Anchor',
		text: 'Connect your Anchor feed to your Marico homepage.',
		finish: true,
		discount: { isDiscount: false, percentNum: 0 },
		chooseSubscription: [
			{
				title: 'Personal',
				text: 'Ideal for individual developers, education and open source communities.',
				price: 0,
				subopportunity: '',
				opportunity: [
					'Anchor Desktop',
					'Unlimited public repositories',
					'Anchor Feeds Engine + Kubernetes',
					'200 image pulls per 6 hours',
					'Unlimited scoped tokens',
				],
			},
			{
				title: 'Pro',
				text: 'Includes pro tools for individual developers who want to accelerate their productivity.',
				price: 60,
				subopportunity: 'Everything in Personal plus:',
				opportunity: [
					'Unlimited private repositories',
					'5,000 image pulls per day',
					'5 concurrent builds',
					'300 Hub vulnerability scans',
				],
			},
			{
				title: 'Expert',
				text: 'Ideal for expert and include capabilitie for collaboration and productivity.',
				price: 160,
				subopportunity: 'Everything in Pro plus:',
				opportunity: [
					'Up to 100 users',
					'Unlimited teams',
					'15 concurrent builds',
					'Add users in bulk',
					'Audit logs',
				],
			},
		],
	},
	{
		blogId: '9',
		title: 'Apple Podcasts',
		text: 'Connect your Apple Podcast to your Marico homepage.',
		finish: true,
		discount: { isDiscount: false, percentNum: 0 },
		chooseSubscription: [
			{
				title: 'Personal',
				text: 'Ideal for individual developers, education and open source communities.',
				price: 0,
				subopportunity: '',
				opportunity: [
					'Apple Podcasts Desktop',
					'Unlimited public repositories',
					'Apple Podcasts Feeds Engine + Kubernetes',
					'200 image pulls per 6 hours',
					'Unlimited scoped tokens',
				],
			},
			{
				title: 'Pro',
				text: 'Includes pro tools for individual developers who want to accelerate their productivity.',
				price: 60,
				subopportunity: 'Everything in Personal plus:',
				opportunity: [
					'Unlimited private repositories',
					'5,000 image pulls per day',
					'5 concurrent builds',
					'300 Hub vulnerability scans',
				],
			},
			{
				title: 'Expert',
				text: 'Ideal for expert and include capabilitie for collaboration and productivity.',
				price: 160,
				subopportunity: 'Everything in Pro plus:',
				opportunity: [
					'Up to 100 users',
					'Unlimited teams',
					'15 concurrent builds',
					'Add users in bulk',
					'Audit logs',
				],
			},
		],
	},
	{
		blogId: '10',
		title: 'Instagram',
		text: 'Connect your Instagram feed to your Marico homepage.',
		finish: true,
		discount: { isDiscount: false, percentNum: 0 },
		chooseSubscription: [
			{
				title: 'Personal',
				text: 'Ideal for individual developers, education and open source communities.',
				price: 0,
				subopportunity: '',
				opportunity: [
					'Instagram Desktop',
					'Unlimited public repositories',
					'Instagrams Feeds Engine + Kubernetes',
					'200 image pulls per 6 hours',
					'Unlimited scoped tokens',
				],
			},
			{
				title: 'Pro',
				text: 'Includes pro tools for individual developers who want to accelerate their productivity.',
				price: 60,
				subopportunity: 'Everything in Personal plus:',
				opportunity: [
					'Unlimited private repositories',
					'5,000 image pulls per day',
					'5 concurrent builds',
					'300 Hub vulnerability scans',
				],
			},
			{
				title: 'Expert',
				text: 'Ideal for expert and include capabilitie for collaboration and productivity.',
				price: 160,
				subopportunity: 'Everything in Pro plus:',
				opportunity: [
					'Up to 100 users',
					'Unlimited teams',
					'15 concurrent builds',
					'Add users in bulk',
					'Audit logs',
				],
			},
		],
	},
	{
		blogId: '11',
		title: 'Linkedin',
		text: 'Connect your Linkedin feed to your Marico homepage.',
		finish: true,
		discount: { isDiscount: false, percentNum: 0 },
		chooseSubscription: [
			{
				title: 'Personal',
				text: 'Ideal for individual developers, education and open source communities.',
				price: 0,
				subopportunity: '',
				opportunity: [
					'Linkedin Desktop',
					'Unlimited public repositories',
					'Linkedins Feeds Engine + Kubernetes',
					'200 image pulls per 6 hours',
					'Unlimited scoped tokens',
				],
			},
			{
				title: 'Pro',
				text: 'Includes pro tools for individual developers who want to accelerate their productivity.',
				price: 60,
				subopportunity: 'Everything in Personal plus:',
				opportunity: [
					'Unlimited private repositories',
					'5,000 image pulls per day',
					'5 concurrent builds',
					'300 Hub vulnerability scans',
				],
			},
			{
				title: 'Expert',
				text: 'Ideal for expert and include capabilitie for collaboration and productivity.',
				price: 160,
				subopportunity: 'Everything in Pro plus:',
				opportunity: [
					'Up to 100 users',
					'Unlimited teams',
					'15 concurrent builds',
					'Add users in bulk',
					'Audit logs',
				],
			},
		],
	},
	{
		blogId: '12',
		title: 'Fackbook',
		text: 'Connect your Fackbook feed to your Marico homepage.',
		finish: true,
		discount: { isDiscount: false, percentNum: 0 },
		chooseSubscription: [
			{
				title: 'Personal',
				text: 'Ideal for individual developers, education and open source communities.',
				price: 0,
				subopportunity: '',
				opportunity: [
					'Fackbook Desktop',
					'Unlimited public repositories',
					'Fackbooks Feeds Engine + Kubernetes',
					'200 image pulls per 6 hours',
					'Unlimited scoped tokens',
				],
			},
			{
				title: 'Pro',
				text: 'Includes pro tools for individual developers who want to accelerate their productivity.',
				price: 60,
				subopportunity: 'Everything in Personal plus:',
				opportunity: [
					'Unlimited private repositories',
					'5,000 image pulls per day',
					'5 concurrent builds',
					'300 Hub vulnerability scans',
				],
			},
			{
				title: 'Expert',
				text: 'Ideal for expert and include capabilitie for collaboration and productivity.',
				price: 160,
				subopportunity: 'Everything in Pro plus:',
				opportunity: [
					'Up to 100 users',
					'Unlimited teams',
					'15 concurrent builds',
					'Add users in bulk',
					'Audit logs',
				],
			},
		],
	},
];
